import { Metadata } from "next";

export { default } from "@/containers/procedure";

export const metadata: Metadata = {
  title: "Best Animals",
  description: "Generated by create next app",
  icons: {
    icon: "/images/favicon.png",
  },
};
