import { Suspense } from "react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/react";
import StyledComponentsRegistry from "./lib/registry";
import Providers from "./Providers";
import Header from "../components/Header";
import Footer from "../components/Footer";
import type { Metadata } from "next";
import "@/styles/globals.css";
import Loading from "./loading";

export const metadata: Metadata = {
  title: "Best Animals",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body>
        <Suspense fallback={<Loading />}>
          <Providers>
            <StyledComponentsRegistry>
              <Header />
              {children}
              <Footer />
            </StyledComponentsRegistry>
          </Providers>
        </Suspense>
        <SpeedInsights />
        <Analytics />
      </body>
    </html>
  );
}
