import Header from "../components/Header";
import Footer from "../components/Footer";
import "@/styles/globals.css";
import ClientProviders from "./ClientProviders";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Best Animals",
  description: "Generated by create next app",
  icons: {
    icon: "/images/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body>
        <ClientProviders>
          <Header />
          {children}
          <Footer />
        </ClientProviders>
      </body>
    </html>
  );
}
