import AdoptionDetail from "@/containers/adoptionDetail";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Best Animals",
  description: "Generated by create next app",
  icons: {
    icon: "/images/favicon.png",
  },
};

const AdoptionDetailPage = () => {
  return (
    <>
      <AdoptionDetail />
    </>
  );
};

export default AdoptionDetailPage;
