import { Suspense } from "react";

import StyledComponentsRegistry from "./lib/registry";
import Providers from "./Providers";
import Header from "./_common/Header";
import Footer from "./_common/Footer";
import type { Metadata } from "next";
import "@/styles/globals.css";
import Loading from "./loading";

export const metadata: Metadata = {
  title: "Best Animals",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body>
        <Suspense fallback={<Loading />}>
          <Providers>
            <StyledComponentsRegistry>
              <Header />
              {children}
              <Footer />
            </StyledComponentsRegistry>
          </Providers>
        </Suspense>
      </body>
    </html>
  );
}
